version: "3.8"
services:
  mysql:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - TZ=Asia/Tokyo
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # volumes:
    #   - ./docker/development/db/data:/var/lib/mysql
    #   - ./docker/development/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #   - ./docker/development/db/sql:/docker-entrypoint-initdb.d
  app:
    image: app:latest
    ports:
      - "8080:8080"
    container_name: app